services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0.4-noble
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
  redis:
    container_name: redis
    image: redis:7.4-alpine
    ports:
      - 6379:6379

volumes:
  mongo-volume: {}
