version: "3.4"

services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.2
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

volumes:
  mongo-volume: {}
