apiVersion: batch/v1
kind: CronJob
metadata:
  name: word-squad-fof
spec:
  schedule: "*/20 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: word-squad-fof
              image: ghcr.io/raynix/word-squad:dev-12374756364
              command:
                - python
                - fof-job.py
              envFrom:
                - secretRef:
                    name: word-squad-env
              resources:
                requests:
                  memory: 200Mi
                  cpu: 200m
          restartPolicy: Never
