apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-squad
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: word-squad
  template:
    metadata:
      labels:
        app: word-squad
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: word-squad
          image: ghcr.io/raynix/word-squad:dev-12363814455
          envFrom:
            - secretRef:
                name: word-squad-env
          env:
            - name: PROD
              value: "true"
            - name: REDIS_HOST
              value: "redis"
          ports:
            - name: http-word-squad
              containerPort: 8000
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
          livenessProbe:
            tcpSocket:
              port: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
