---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oewn-mysql
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: oewn-mysql
  template:
    metadata:
      labels:
        app: oewn-mysql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - word-squad
                topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: config
          configMap:
            name: mysql
      containers:
        - name: oewn-mysql
          image: raynix/oewn-mysql:latest
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pass
          volumeMounts:
            - name: config
              mountPath: /etc/mysql/conf.d
          resources:
            requests:
              memory: 500Mi
              cpu: 400m
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 300
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 300
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: oewn-mysql
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: oewn-mysql
