apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: "redis:7.4-alpine"
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          livenessProbe:
            tcpSocket:
              port: redis
          readinessProbe:
            tcpSocket:
              port: redis
          resources:
            limits:
              cpu: "1.0"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 200Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
