apiVersion: v1
kind: Service
metadata:
  name: word-squad
spec:
  ports:
    - name: http-word-squad
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: word-squad

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: word-squad
spec:
  parentRefs:
    - kind: Gateway
      name: kubernetes-gateway
      namespace: istio-system
  hostnames:
    - wordsquad.awes.one
  rules:
    - backendRefs:
        - name: word-squad
          port: 8000
