apiVersion: v1
kind: Service
metadata:
  name: word-squad
spec:
  ports:
    - name: http_word_squad
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: word-squad
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: word-squad
spec:
  gateways:
    - istio-system/awes-gateway
  hosts:
    - wordsquad.awes.one
  http:
    - route:
        - destination:
            host: word-squad
            port:
              number: 8000
