name: ci

on:
  push:
    branches:
      - 'main'

env:
  build_tag: dev-${{ github.run_id }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/raynix/word-squad:${{ env.build_tag }}
      - name: Update deployment version
        run: |
          sed -i -E "s|(image: ghcr.io/raynix/word-squad:).*|\1${{ env.build_tag }}|g" .kustomize/deploy.yaml
      - name: Auto commit & push changes
        run: |
          git config --global user.name 'raynix Bot'
          git config --global user.email 'raynix@gmail.com'
          git commit -am "Automated commit"
          git push
