name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - wordSquad/**
      - Dockerfile

env:
  build_tag: dev-${{ github.run_id }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/raynix/word-squad:${{ env.build_tag }}
      - name: Update deployment version
        run: |
          pwd
          ls -lht
          sed -i -E "s|(newTag: ).*|\1${{ env.build_tag }}|g" .kustomize/kustomization.yaml
      - name: Auto commit & push changes
        run: |
          git config --global user.name 'raynix Bot'
          git config --global user.email 'raynix@gmail.com'
          git commit -am "Automated commit"
          git push
